# Generated by Django 5.2.6 on 2025-09-04 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('initialSurvey', '0002_survey_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, unique=True)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('survey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='initialSurvey.survey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
