# Generated by Django 5.2.6 on 2025-09-03 21:31

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('WorkExperience', models.TextField(max_length=500)),
                ('Education', models.TextField(max_length=500)),
                ('TecnicalSkills', models.TextField(max_length=500)),
                ('SoftSkills', models.TextField(max_length=500)),
                ('Languages', models.TextField(max_length=500)),
                ('Preferences', multiselectfield.db.fields.MultiSelectField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('flexible', 'Flexible hours')], max_length=200)),
            ],
        ),
    ]
